### ISSUE TITLE
Running into error

### ISSUE THREAD

**Issue by xray1111** [dips4717/gcn-cnn#3]
When running command line:

```
python train.py --batch_size 10 --decoder_model strided --dim 1024 --use_directed_graph True 
--use_precomputed_25Chan_imgs True --Channel25_img_dir data/25ChanImages
```

Exception raised from Channel25_strided.py, line 182:

```
#get the embeddings 
#obj_embed = self.obj_embed(obj_labels)
obj_embed = self.obj_embed(obj_labels.type(torch.LongTensor)) # Windows fix
rela_embed = rela_feats

```        

Error information:

Traceback (most recent call last):
  File "/home/xray/.conda/envs/DB/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xray/.conda/envs/DB/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xray/.vscode-server/extensions/ms-python.python-2021.2.625869727/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/xray/.vscode-server/extensions/ms-python.python-2021.2.625869727/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/xray/.vscode-server/extensions/ms-python.python-2021.2.625869727/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/xray/.conda/envs/DB/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/xray/.conda/envs/DB/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/xray/.conda/envs/DB/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xray/homework/geometric_matching/gcn-cnn/train.py", line 278, in <module>
    main(opt)
  File "/home/xray/homework/geometric_matching/gcn-cnn/train.py", line 146, in main
    _, out = model(sg_data)
  File "/home/xray/.conda/envs/DB/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xray/homework/geometric_matching/gcn-cnn/models/Channel25_strided.py", line 184, in forward
    obj_embed = self.obj_embed(obj_labels.type(torch.LongTensor)) # Windows fix
  File "/home/xray/.conda/envs/DB/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xray/.conda/envs/DB/lib/python3.8/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/xray/.conda/envs/DB/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xray/.conda/envs/DB/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 112, in forward
    return F.embedding(
  File "/home/xray/.conda/envs/DB/lib/python3.8/site-packages/torch/nn/functional.py", line 1484, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected object of device type cuda but got device type cpu for argument #3 'index' in call to _th_index_select
Terminating BlobFetcher

**Comment by dips4717** [comment]
Should be fixed now!
